version: "3"

services:
    janusgraph-fdb:
        build:
            context: ../services/janusgraph-fdb
            args:
                VERSION: latest
        ports:
            - "8182:8182"
        depends_on:
            - foundationdb
            - solr
        volumes:
            - clusterfile:/etc/foundationdb
        environment:
            - janusgraph.storage.backend=com.experoinc.janusgraph.diskstorage.foundationdb.FoundationDBStoreManager
            - janusgraph.storage.hostname=foundationdb
              - janusgraph.storage.fdb.isolation-level=serializable
              #- janusgraph.storage.fdb.isolation-level=read_committed_with_write # not to use for production
            - janusgraph.index.search.backend=solr
            - janusgraph.index.search.solr.mode=cloud
            - janusgraph.index.search.solr.zookeeper-url=zookeeper:2181

    gremlin-client:
        build:
            context: ../services/gremlin-client
            args:
                VERSION: latest
        stdin_open: true
        environment:
            - GREMLIN_REMOTE_HOSTS=janusgraph-fdb
        depends_on:
            - janusgraph-fdb

    foundationdb:
        build:
            context: ../services/foundationdb
            args:
                VERSION: 6.2.11
        environment:
            - FDB_CLUSTER_FILE=/var/fdb/share/fdb.cluster
        volumes:
            - clusterfile:/var/fdb/share
        ports:
            - "4500:4500"

    solr:
        build:
            context: ../services/solr
            args:
                VERSION: 7.7.2
        environment:
            - ZK_HOST=zookeeper:2181
        ports:
            - "8983:8983"
        depends_on:
            - zookeeper

    # from: https://github.com/docker-solr/docker-solr-examples/blob/master/docker-compose/docker-compose.yml
    zookeeper:
        build:
            context: ../services/zookeeper
            args:
                VERSION: 3.5
        restart: always
        environment:
            ZOO_MY_ID: 1
            ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181
        ports:
            - "2181:2181"

volumes:
    clusterfile:
        driver: local
