version: "3"

services:
    janusgraph-fdb:
        image: artifactory.gdata.de:6555/development/gaia/janusbench/janusgraph-fdb:0.4.0
        build:
            context: ../services/janusgraph-fdb
            args:
                VERSION: latest
        ports:
            - "8182:8182"
        depends_on:
            - foundationdb
            - elasticsearch
        volumes:
            - clusterfile:/etc/foundationdb
        environment:
            - janusgraph.storage.backend=com.experoinc.janusgraph.diskstorage.foundationdb.FoundationDBStoreManager
            - janusgraph.storage.hostname=foundationdb
            - janusgraph.storage.fdb.isolation-level=read_committed_with_write # not to use for production
            # - janusgraph.storage.fdb.isolation-level=serializable
 
            - janusgraph.index.search.backend=elasticsearch
            - janusgraph.index.search.hostname=elasticsearch
            - janusgraph.index.search.elasticsearch.client-only=true

            - janusgraph.cache.db-cache=true

    gremlin-client:
        image: artifactory.gdata.de:6555/development/gaia/janusbench/gremlin-client:0.4.0-1
        build:
            context: ../services/gremlin-client
            args:
                VERSION: latest
        stdin_open: true
        environment:
            - GREMLIN_REMOTE_HOSTS=janusgraph-fdb
        depends_on:
            - janusgraph-fdb

    foundationdb:
        image: artifactory.gdata.de:6555/development/gaia/janusbench/foundationdb:6.2.11
        build:
            context: ../services/foundationdb
            args:
                VERSION: 6.2.11
        environment:
            - FDB_CLUSTER_FILE=/var/fdb/share/fdb.cluster
        volumes:
            - clusterfile:/var/fdb/share
        ports:
            - "4500:4500"

    # from sunsided/janusgraph-docker
    elasticsearch:
        image: artifactory.gdata.de:6555/development/gaia/janusbench/elasticsearch:6.6.0
        build:
            context: ../services/elasticsearch
            args:
                VERSION: 6.6.0
        ports:
            - "9200:9200"
            - "9300:9300"

volumes:
    clusterfile:
        driver: local
