version: "3"

services:
    janusgraph:
        image: artifactory.gdata.de:6555/development/gaia/janusbench/janusgraph:0.4.0
        build:
            context: ../services/janusgraph
            args:
                VERSION: 0.4.0
        ports:
            - "8182:8182"
        depends_on:
            - hbase
        environment:
            - janusgraph.storage.backend=hbase
            - janusgraph.storage.hostname=hbase
            - JANUS_STORAGE_TIMEOUT=50 # hbase takes longer than other backends

            - janusgraph.index.search.backend=lucene
            - janusgraph.index.search.directory=/tmp/searchindex

            - janusgraph.cache.db-cache=true

    gremlin-client:
        image: artifactory.gdata.de:6555/development/gaia/janusbench/gremlin-client:0.4.0-4
        build:
            context: ../services/gremlin-client
            args:
                VERSION: 0.4.0
        stdin_open: true
        environment:
            - GREMLIN_REMOTE_HOSTS=janusgraph
        depends_on:
            - janusgraph
        volumes:
            - ../services/gremlin-client/src:/data

    hbase:
        image: artifactory.gdata.de:6555/development/gaia/janusbench/hbase:2.1
        build:
            context: ../services/hbase
            args:
                VERSION: 2.1
        ports:
            - "16010:16010" # Master Server
            - "9095:9095" # Thrift
            - "8085:8085" # REST server UI
