version: "3"

services:
    janusgraph:
        build:
            context: ../services/janusgraph
            args:
                VERSION: latest
        ports:
            - "8182:8182"
        depends_on:
            - solr
        environment:
            - janusgraph.storage.backend=berkeleyje
            - janusgraph.storage.directory=/db/berkeley
            - janusgraph.index.search.backend=solr
            - janusgraph.index.search.solr.mode=cloud
            - janusgraph.index.search.solr.zookeeper-url=zookeeper:2181

    gremlin-client:
        build:
            context: ../services/gremlin-client
            args:
                VERSION: latest
        stdin_open: true
        depends_on:
            - janusgraph

    solr:
        build:
            context: ../services/solr
            args:
                VERSION: 7.7.2
        environment:
            - ZK_HOST=zookeeper:2181
        ports:
            - "8983:8983"
        depends_on:
            - zookeeper

    # from: https://github.com/docker-solr/docker-solr-examples/blob/master/docker-compose/docker-compose.yml
    zookeeper:
        build:
            context: ../services/zookeeper
            args:
                VERSION: 3.5
        restart: always
        environment:
            ZOO_MY_ID: 1
            ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181
        ports:
            - "2181:2181"
