version: "3"

services:
    janusgraph:
        image: artifactory.gdata.de:6555/development/gaia/janusbench/janusgraph:0.4.0-1
        build:
            context: ../services/janusgraph
            args:
                VERSION: latest
        ports:
            - "8182:8182"
        depends_on:
            - hbase
            - elasticsearch
        environment:
            - janusgraph.storage.backend=hbase
            - janusgraph.storage.hostname=hbase
            - JANUS_STORAGE_TIMEOUT=50 # hbase takes longer than other backends

            - janusgraph.index.search.backend=elasticsearch
            - janusgraph.index.search.hostname=elasticsearch
            - janusgraph.index.search.elasticsearch.client-only=true

            - janusgraph.cache.db-cache=true

    gremlin-client:
        image: artifactory.gdata.de:6555/development/gaia/janusbench/gremlin-client:0.4.0-3
        build:
            context: ../services/gremlin-client
            args:
                VERSION: latest
        stdin_open: true
        environment:
            - GREMLIN_REMOTE_HOSTS=janusgraph
        depends_on:
            - janusgraph

    hbase:
        image: artifactory.gdata.de:6555/development/gaia/janusbench/hbase:2.1
        build:
            context: ../services/hbase
            args:
                VERSION: 2.1
        ports:
            - "16010:16010" # Master Server
            - "9095:9095" # Thrift
            - "8085:8085" # REST server UI

    # from sunsided/janusgraph-docker
    elasticsearch:
        image: artifactory.gdata.de:6555/development/gaia/janusbench/elasticsearch:6.6.0
        build:
            context: ../services/elasticsearch
            args:
                VERSION: 6.6.0
        ports:
            - "9200:9200"
            - "9300:9300"
