version: "3"

services:
    janusgraph:
        image: artifactory.gdata.de:6555/development/gaia/janusbench/janusgraph:0.4.0
        build:
            context: ../services/janusgraph
            args:
                VERSION: latest
        ports:
            - "8182:8182"
        depends_on:
            - scylla
            - solr
        environment:
            - janusgraph.storage.backend=cql
            - janusgraph.storage.hostname=scylla

            - janusgraph.index.search.backend=solr
            - janusgraph.index.search.solr.mode=cloud
            - janusgraph.index.search.solr.zookeeper-url=zookeeper:2181

            - janusgraph.cache.db-cache=true

    gremlin-client:
        image: artifactory.gdata.de:6555/development/gaia/janusbench/gremlin-client:0.4.0-2
        build:
            context: ../services/gremlin-client
            args:
                VERSION: latest
        stdin_open: true
        environment:
            - GREMLIN_REMOTE_HOSTS=janusgraph
        depends_on:
            - janusgraph

    # from sunsided/janusgraph-docker
    scylla:
        image: artifactory.gdata.de:6555/development/gaia/janusbench/scylla:3.0.8-1
        build:
            context: ../services/scylla
            args:
                VERSION: 3.0.8
        ports:
            # http://docs.scylladb.com/kb/posix/
            - "10000:10000" # REST API
            - "9042:9042" # CQL ports (native_transport_port)
            - "9160:9160" # Thrift (rpc_port)
            - "7000:7000" # Internode
            - "7001:7001"
            - "7199:7199" # JMX
            - "9180:9180" # Prometheus monitoring
            - "9100:9100"

    solr:
        image: artifactory.gdata.de:6555/development/gaia/janusbench/solr:7.7.2
        build:
        build:
            context: ../services/solr
            args:
                VERSION: 7.7.2
        environment:
            - ZK_HOST=zookeeper:2181
        ports:
            - "8983:8983"
        depends_on:
            - zookeeper

    # from: https://github.com/docker-solr/docker-solr-examples/blob/master/docker-compose/docker-compose.yml
    zookeeper:
        image: artifactory.gdata.de:6555/development/gaia/janusbench/zookeeper:3.5
        build:
            context: ../services/zookeeper
            args:
                VERSION: 3.5
        restart: always
        environment:
            ZOO_MY_ID: 1
            ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181
        ports:
            - "2181:2181"
