version: "3"

services:
    janusgraph:
        image: artifactory.gdata.de:6555/development/gaia/janusbench/janusgraph:0.4.0
        build:
            context: ../services/janusgraph
            args:
                VERSION: latest
        ports:
            - "8182:8182"
        depends_on:
            - hbase
            - solr
        environment:
            - janusgraph.storage.backend=hbase
            - janusgraph.storage.hostname=hbase
            - JANUS_STORAGE_TIMEOUT=50 # hbase takes longer than other backends

            - janusgraph.index.search.backend=solr
            - janusgraph.index.search.solr.mode=cloud
            - janusgraph.index.search.solr.zookeeper-url=zookeeper:2181

            - janusgraph.cache.db-cache=true

    gremlin-client:
        image: artifactory.gdata.de:6555/development/gaia/janusbench/gremlin-client:0.4.0
        build:
            context: ../services/gremlin-client
            args:
                VERSION: latest
        stdin_open: true
        environment:
            - GREMLIN_REMOTE_HOSTS=janusgraph
        depends_on:
            - janusgraph

    hbase:
        image: artifactory.gdata.de:6555/development/gaia/janusbench/hbase:2.1
        build:
            context: ../services/hbase
            args:
                VERSION: 2.1
        ports:
            - "16010:16010" # Master Server
            - "9095:9095" # Thrift
            - "8085:8085" # REST server UI

    solr:
        image: artifactory.gdata.de:6555/development/gaia/janusbench/solr:7.7.2
        build:
            context: ../services/solr
            args:
                VERSION: 7.7.2
        environment:
            - ZK_HOST=zookeeper:2181
        ports:
            - "8983:8983"
        depends_on:
            - zookeeper

    # from: https://github.com/docker-solr/docker-solr-examples/blob/master/docker-compose/docker-compose.yml
    zookeeper:
        image: artifactory.gdata.de:6555/development/gaia/janusbench/zookeeper:3.5
        build:
            context: ../services/zookeeper
            args:
                VERSION: 3.5
        restart: always
        environment:
            ZOO_MY_ID: 1
            ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181
        ports:
            - "2181:2181"
