version: "3"

services:
    janusgraph:
        image: artifactory.gdata.de:6555/development/gaia/janusbench/janusgraph:0.4.0
        build:
            context: ../services/janusgraph
            args:
                VERSION: latest
        ports:
            - "8182:8182"
        depends_on:
            - cassandra
        environment:
            - janusgraph.storage.backend=cql
            - janusgraph.storage.hostname=cassandra

            - janusgraph.cache.db-cache=true

    gremlin-client:
        image: artifactory.gdata.de:6555/development/gaia/janusbench/gremlin-client:0.4.0-2
        build:
            context: ../services/gremlin-client
            args:
                VERSION: latest
        stdin_open: true
        environment:
            - GREMLIN_REMOTE_HOSTS=janusgraph
        depends_on:
            - janusgraph

    cassandra:
        image: artifactory.gdata.de:6555/development/gaia/janusbench/cassandra:3.11
        build:
            context: ../services/cassandra
            args:
                VERSION: 3.11
        ports:
            - "9042:9042" # CQL ports (native_transport_port)
            - "9160:9160" # Thrift (rpc_port)
            - "7000:7000" # Internode
            - "7001:7001"
            - "7199:7199"
