version: "3"

services:
    janusgraph:
        image: artifactory.gdata.de:6555/development/gaia/janusbench/janusgraph-fdb:0.5.0
        build:
            context: ../services/janusgraph-fdb
            args:
                VERSION: 0.5.0
        ports:
            - "8182:8182"
        depends_on:
            - cassandra
        environment:
            - janusgraph.storage.backend=cql
            - janusgraph.storage.hostname=cassandra

            - janusgraph.cache.db-cache=true
        volumes:
            - /tmp/janusbench/:/tmp/janusbench/

    gremlin-client:
        image: artifactory.gdata.de:6555/development/gaia/janusbench/gremlin-client:0.5.0
        build:
            context: ../services/gremlin-client
            args:
                VERSION: 0.5.0
        stdin_open: true
        environment:
            - GREMLIN_REMOTE_HOSTS=janusgraph
        depends_on:
            - janusgraph
        volumes:
            - ../services/gremlin-client/src:/data

    cassandra:
        image: artifactory.gdata.de:6555/development/gaia/janusbench/cassandra:3.11
        build:
            context: ../services/cassandra
            args:
                VERSION: 3.11
        ports:
            - "9042" # CQL ports (native_transport_port)
            - "9160" # Thrift (rpc_port)
            - "7000" # Internode
            - "7001"
            - "7199"
