version: "3"

services:
    janusgraph:
        image: artifactory.gdata.de:6555/development/gaia/janusbench/janusgraph:0.4.0-1
        build:
            context: ../services/janusgraph
            args:
                VERSION: 0.4.0
        ports:
            - "8182:8182"
        depends_on:
            - cassandra
            - solr
        environment:
            - janusgraph.storage.backend=cql
            - janusgraph.storage.hostname=cassandra

            - janusgraph.index.search.backend=solr
            - janusgraph.index.search.solr.mode=cloud
            - janusgraph.index.search.solr.zookeeper-url=zookeeper:2181

            - janusgraph.cache.db-cache=true

    gremlin-client:
        image: artifactory.gdata.de:6555/development/gaia/janusbench/gremlin-client:0.4.0-4
        build:
            context: ../services/gremlin-client
            args:
                VERSION: 0.4.0
        stdin_open: true
        environment:
            - GREMLIN_REMOTE_HOSTS=janusgraph
        depends_on:
            - janusgraph
        volumes:
            - ../services/gremlin-client/src:/data

    cassandra:
        image: artifactory.gdata.de:6555/development/gaia/janusbench/cassandra:3.11
        build:
            context: ../services/cassandra
            args:
                VERSION: 3.11
        ports:
            - "9042" # CQL ports (native_transport_port)
            - "9160" # Thrift (rpc_port)
            - "7000" # Internode
            - "7001"
            - "7199"

    solr:
        image: artifactory.gdata.de:6555/development/gaia/janusbench/solr:7.7.2
        build:
        build:
            context: ../services/solr
            args:
                VERSION: 7.7.2
        environment:
            - ZK_HOST=zookeeper:2181
        ports:
            - "8983"
        depends_on:
            - zookeeper

    # from: https://github.com/docker-solr/docker-solr-examples/blob/master/docker-compose/docker-compose.yml
    zookeeper:
        image: artifactory.gdata.de:6555/development/gaia/janusbench/zookeeper:3.5
        build:
            context: ../services/zookeeper
            args:
                VERSION: 3.5
        restart: always
        environment:
            ZOO_MY_ID: 1
            ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181
        ports:
            - "2181"
