version: "3"

services:
    janusgraph:
        image: artifactory.gdata.de:6555/development/gaia/janusbench/janusgraph-fdb:0.5.0
        build:
            context: ../services/janusgraph-fdb
            args:
                VERSION: 0.5.0
        ports:
            - "8182:8182"
        depends_on:
            - solr
        environment:
            - janusgraph.storage.backend=berkeleyje
            - janusgraph.storage.directory=/tmp/berkeleyje

            - janusgraph.index.search.backend=solr
            - janusgraph.index.search.solr.mode=cloud
            - janusgraph.index.search.solr.zookeeper-url=zookeeper:2181

            - janusgraph.cache.db-cache=true
        volumes:
            - /tmp/janusbench/:/tmp/janusbench/

    gremlin-client:
        image: artifactory.gdata.de:6555/development/gaia/janusbench/gremlin-client:0.5.0
        build:
            context: ../services/gremlin-client
            args:
                VERSION: 0.5.0
        stdin_open: true
        environment:
            - GREMLIN_REMOTE_HOSTS=janusgraph
        depends_on:
            - janusgraph
        volumes:
            - ../services/gremlin-client/src:/data

    solr:
        image: artifactory.gdata.de:6555/development/gaia/janusbench/solr:7.7.2
        build:
            context: ../services/solr
            args:
                VERSION: 7.7.2
        environment:
            - ZK_HOST=zookeeper:2181
        ports:
            - "8983"
        depends_on:
            - zookeeper

    # from: https://github.com/docker-solr/docker-solr-examples/blob/master/docker-compose/docker-compose.yml
    zookeeper:
        image: artifactory.gdata.de:6555/development/gaia/janusbench/zookeeper:3.5
        build:
            context: ../services/zookeeper
            args:
                VERSION: 3.5
        restart: always
        environment:
            ZOO_MY_ID: 1
            ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181
        ports:
            - "2181"
