version: "3"

services:
    janusgraph:
        image: artifactory.gdata.de:6555/development/gaia/janusbench/janusgraph-fdb:0.5.0
        build:
            context: ../services/janusgraph-fdb
            args:
                VERSION: 0.5.0
        ports:
            - "8182:8182"
        depends_on:
            - scylla
            - elasticsearch
        environment:
            - janusgraph.storage.backend=cql
            - janusgraph.storage.hostname=scylla

            - janusgraph.index.search.backend=elasticsearch
            - janusgraph.index.search.hostname=elasticsearch
            - janusgraph.index.search.elasticsearch.client-only=true

            - janusgraph.cache.db-cache=true
        volumes:
            - /tmp/janusbench/:/tmp/janusbench/

    gremlin-client:
        image: artifactory.gdata.de:6555/development/gaia/janusbench/gremlin-client:0.5.0
        build:
            context: ../services/gremlin-client
            args:
                VERSION: 0.5.0
        stdin_open: true
        environment:
            - GREMLIN_REMOTE_HOSTS=janusgraph
        depends_on:
            - janusgraph
        volumes:
            - ../services/gremlin-client/src:/data

    # from sunsided/janusgraph-docker
    scylla:
        image: artifactory.gdata.de:6555/development/gaia/janusbench/scylla:3.0.8-1
        build:
            context: ../services/scylla
            args:
                VERSION: 3.0.8
        ports:
            # http://docs.scylladb.com/kb/posix/
            - "10000" # REST API
            - "9042" # CQL ports (native_transport_port)
            - "9160" # Thrift (rpc_port)
            - "7000" # Internode
            - "7001"
            - "7199" # JMX
            - "9180" # Prometheus monitoring
            - "9100"

    # from sunsided/janusgraph-docker
    elasticsearch:
        image: artifactory.gdata.de:6555/development/gaia/janusbench/elasticsearch:6.6.0
        build:
            context: ../services/elasticsearch
            args:
                VERSION: 6.6.0
        ports:
            - "9200"
            - "9300"
