version: "3"

services:
    janusgraph:
        image: artifactory.gdata.de:6555/development/gaia/janusbench/janusgraph:0.4.0-1
        build:
            context: ../services/janusgraph
            args:
                VERSION: 0.4.0
        ports:
            - "8182:8182"
        depends_on:
            - elasticsearch
        environment:
            - janusgraph.storage.backend=berkeleyje
            - janusgraph.storage.directory=/tmp/berkeleyje
            - janusgraph.index.search.backend=elasticsearch
            - janusgraph.index.search.hostname=elasticsearch
            - janusgraph.index.search.elasticsearch.client-only=true

            - janusgraph.cache.db-cache=true

    gremlin-client:
        image: artifactory.gdata.de:6555/development/gaia/janusbench/gremlin-client:0.4.0-4
        build:
            context: ../services/gremlin-client
            args:
                VERSION: 0.4.0
        stdin_open: true
        environment:
            - GREMLIN_REMOTE_HOSTS=janusgraph
        depends_on:
            - janusgraph
        volumes:
            - ../services/gremlin-client/src:/data

    # from sunsided/janusgraph-docker
    elasticsearch:
        image: artifactory.gdata.de:6555/development/gaia/janusbench/elasticsearch:6.6.0
        build:
            context: ../services/elasticsearch
            args:
                VERSION: 6.6.0
        ports:
            - "9200"
            - "9300"
